Repository vuhuy194779/Agile-Web-Dev-CITS5505, pull requests merged in 2025-05, with the labels that each got.

#36 Reference add to readme
  README.md
Labels: documentation

#40 Fix period overlap calendar
  README.md
  web/app/static/visualize.css
Labels: bug fix

#41 Add end file newline to all file
  .gitignore
  deliverables/first/visualize.css
  deliverables/first/visualize.html
  deliverables/first/visualize.js
  web/app/templates/welcome-page.html
Labels: enhancement

#44 add acknowledge
  README.md
Labels: documentation

#45 Update README.md
  README.md
Labels: documentation
